"""add mbid column to Release

Revision ID: 4275830d09e7
Revises: 9cfd0debf519
Create Date: 2025-05-30 20:21:02.920275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4275830d09e7'
down_revision = '9cfd0debf519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_release_mbid'), ['mbid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_mbid'))
        batch_op.drop_column('mbid')

    # ### end Alembic commands ###
