"""add mbid to Track

Revision ID: 8047010fedcb
Revises: 2bafb459fcaa
Create Date: 2025-05-30 23:11:04.239829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8047010fedcb'
down_revision = '2bafb459fcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_track_mbid'), ['mbid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_mbid'))
        batch_op.drop_column('mbid')

    # ### end Alembic commands ###
