"""add mbid column to Band

Revision ID: 9cfd0debf519
Revises: e3dd75f345c5
Create Date: 2025-05-30 20:09:06.876514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfd0debf519'
down_revision = 'e3dd75f345c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_band_mbid'), ['mbid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_mbid'))
        batch_op.drop_column('mbid')

    # ### end Alembic commands ###
