"""Add Band.location/country/label & Release.label/year

Revision ID: e3dd75f345c5
Revises: a66d3f51e66e
Create Date: 2025-05-22 22:07:18.882945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dd75f345c5'
down_revision = 'a66d3f51e66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=False))

    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('label')

    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.drop_column('label')
        batch_op.drop_column('country')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
